resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install mocha'

- task: Npm@1
  displayName: 'npm test'
  inputs:
    command: custom
    verbose: false
    customCommand: test

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: code'
  inputs:
    PathtoPublish: Src
    ArtifactName: code

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: ARM'
  inputs:
    PathtoPublish: Deploy
    ArtifactName: arm

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Tests'
  inputs:
    PathtoPublish: Tests.Integration
    ArtifactName: tests